version: '3.8'

services:
  apache-php:
    build:
      context: ./docker/apache-php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb
      - oracle

  mariadb:
    image: mariadb:11.3
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  oracle:
    image: gvenzl/oracle-free:23
    restart: always
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    ports:
      - "1521:1521"

volumes:
  mariadb_data: